<?php
//Menandai pesan error
$class1="alert alert-danger"; $class2_icon="glyphicon glyphicon-exclamation-sign";
$class2="alert alert-success";
//Kondisi Variabel Ketika Data Kosong 
//Error
$nisnErr = $nama_siswaErr = $jenis_kelaminErr = $tempat_lahirErr = $tanggal_lahirErr = $agama_siswaErr = $status_keluargaErr = $alamat_siswaErr = $hp_siswaErr = $nama_ayahErr = $pendidikan_ayahErr = $pekerjaan_ayahErr = $penghasilan_ayahErr = $hp_ayahErr = $nama_ibuErr = $pendidikan_ibuErr = $pekerjaan_ibuErr = $penghasilan_ibuErr = $hp_ibuErr = $nama_waliErr = $pendidikan_waliErr = $pekerjaan_waliErr = $penghasilan_waliErr = $hp_waliErr = $npsn_sekolahErr = $nama_sekolahErr = $status_sekolahErr = $model_ujianErr = $alamat_sekolahErr = $tahun_lulusErr = $ipaErr = $matematikaErr = $bahasa_indonesiaErr = $bahasa_ingrisErr = $status_pendaftaranErr = $tanggal_pendaftaranErr = ""; 
//Normal
$nisn  = $nama_siswa = $jenis_kelamin = $tempat_lahir = $tanggal_lahir = $agama_siswa = $status_keluarga = $alamat_siswa = $hp_siswa = $nama_ayah = $pendidikan_ayah = $pekerjaan_ayah = $penghasilan_ayah = $hp_ayah = $nama_ibu = $pendidikan_ibu = $pekerjaan_ibu = $penghasilan_ibu = $hp_ibu = $nama_wali = $pendidikan_wali = $pekerjaan_wali = $penghasilan_wali = $hp_wali = $npsn_sekolah = $nama_sekolah = $status_sekolah = $model_ujian = $alamat_sekolah = $tahun_lulus = $ipa = $matematika = $bahasa_indonesia = $bahasa_ingris = $status_pendaftaran = $tanggal_pendaftaran = "";
//BootstrapClass
$nisnClass  = $nama_siswaClass = $jenis_kelaminClass = $tempat_lahirClass = $tanggal_lahirClass = $agama_siswaClass = $status_keluargaClass = $alamat_siswaClass = $hp_siswaClass = $nama_ayahClass = $pendidikan_ayahClass = $pekerjaan_ayahClass = $penghasilan_ayahClass = $hp_ayahClass = $nama_ibuClass = $pendidikan_ibuClass = $pekerjaan_ibuClass = $penghasilan_ibuClass = $hp_ibuClass = $nama_waliClass = $pendidikan_waliClass = $pekerjaan_waliClass = $penghasilan_waliClass = $hp_waliClass = $npsn_sekolahClass = $nama_sekolahClass = $status_sekolahClass = $model_ujianClass = $alamat_sekolahClass = $tahun_lulusClass = $ipaClass = $matematikaClass = $bahasa_indonesiaClass = $bahasa_ingrisClass = $status_pendaftaranClass = $tanggal_pendaftaranClass = "";
$nisnClass_icon  = $nama_siswaClass_icon = $jenis_kelaminClass_icon = $tempat_lahirClass_icon = $tanggal_lahirClass_icon = $agama_siswaClass_icon = $status_keluargaClass_icon = $alamat_siswaClass_icon = $hp_siswaClass_icon = $nama_ayahClass_icon = $pendidikan_ayahClass_icon = $pekerjaan_ayahClass_icon = $penghasilan_ayahClass_icon = $hp_ayahClass_icon = $nama_ibuClass_icon = $pendidikan_ibuClass_icon = $pekerjaan_ibuClass_icon = $penghasilan_ibuClass_icon = $hp_ibuClass_icon = $nama_waliClass_icon = $pendidikan_waliClass_icon = $pekerjaan_waliClass_icon = $penghasilan_waliClass_icon = $hp_waliClass_icon = $npsn_sekolahClass_icon = $nama_sekolahClass_icon = $status_sekolahClass_icon = $model_ujianClass_icon = $alamat_sekolahClass_icon = $tahun_lulusClass_icon = $ipaClass_icon = $matematikaClass_icon = $bahasa_indonesiaClass_icon = $bahasa_ingrisClass_icon = $status_pendaftaranClass_icon = $tanggal_pendaftaranClass_icon = "";
//Database 
$berhasil_simpan = $berhasil_simpanClass = $gagal_simpanErr ="";
$gagal_simpanClass = $gagal_simpanClass_icon = "";
?>